### ISSUE TITLE
PyXB version requirement problem

### ISSUE THREAD

**Issue by danielatdattrixdotcom** [AuthorizeNet/sdk-python#66]
setup.py merely requires PyXB, but use of version 1.2.4 is hard-coded into the code as a requirement. PyXB is at 1.2.5 now and thus installs or upgrades break. You need to specify version in setup.py or remove the hard-coded version check.

**Comment by sunnyrajrathod** [comment]
Thanks. We will look into this in the next release. Sorry for delayed response.

**Comment by witekdev** [comment]
@sunnyrajrathod Has this issue been addressed?

**Comment by sunnyrajrathod** [comment]
Yes, we addressed this in Nov Release - https://github.com/AuthorizeNet/sdk-python/releases/tag/1.0.13.

**Comment by witekdev** [comment]
Thanks for the quick response!

**Comment by witekdev** [comment]
@sunnyrajrathod actually after looking at the code, it seems that you guys just hardcoded the 1.2.5 version into https://github.com/AuthorizeNet/sdk-python/blob/master/authorizenet/apicontractsv1.py
Would it not make sense to also pin this (1.2.5) version in setup.py? Otherwise it seems when pyxb is upgraded again and then one reinstalls authorize.net it will pull the latest version of pyxb and it will be out of sync with what is hardcoded. Thus this exact issue will become an issue again.

**Comment by liveevil** [comment]
Done. Thanks for the help @witekdev 
We'll release with the next update.

**Comment by witekdev** [comment]
Great, thanks!

**Comment by danielatdattrixdotcom** [comment]
Closing since this was indeed fixed.
