### ISSUE TITLE
Errors in documentation - Authorize.Net Accept Hosted

### ISSUE THREAD

**Issue by witekdev** [AuthorizeNet/sdk-python#69]
https://developer.authorize.net/api/reference/features/accept_hosted.html
Under Hosted Form Parameter Settings
```hostedPaymentReturnOptions``` parameters are specified as:
```
{"showReceipt" : "true", "url":"https://mysite.com/receipt", "urlText": "Continue", "cancelUrl": "https://mysite.com/cancel", cancelUrlText: "This request was cancelled."}
```
but need to be:
```
{"showReceipt" : true, "url":"https://mysite.com/receipt", "urlText": "Continue", "cancelUrl": "https://mysite.com/cancel", "cancelUrlText": "This request was cancelled."}
```

This probably applies to other languages but I post here as I'm working with python.

As a side note, is there any python related documentation as to how to implement the Accept Hosted form as a lightbox popup? Or even non-python specific documentation?

**Comment by adavidw** [comment]
The hostedPaymentReturnOptions parameters have since been fixed in the documentation. Only the "true" shows up correctly right now, though. The other change (quotes around "cancelUrlText") has been made in source, but has to wait until the next build of the web site hits the main servers.

There's not really good documentation yet regarding making a lightbox for the form. The documentation has everything you need as long as you can fill in the gaps, but it's not a really great step-by-step guide yet or anything.

In a nutshell, you do a server to server connection to get the token, which you can do using Python following [the sample here](https://github.com/AuthorizeNet/sample-code-python/blob/master/PaymentTransactions/get-an-accept-payment-page.py). Then, in your HTML page, you create an iframe, post the token to our server within the iframe so that the form that comes back in response loads up into the iframe, then put in the rest of the css and code to style that iframe and implement a close box and stuff.

Again, we don't have specific instructions, but you can see it done by examing the html and css in our [sample app](https://github.com/AuthorizeNet/accept-sample-app).
